version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: event_management
      TZ: Asia/Ho_Chi_Minh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} --silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - default

  backend:
    image: tanh11704/event-management-backend:1.0
    container_name: event-management
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=jdbc:mysql://db:3306/event_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_APP_PASSWORD=${MAIL_APP_PASSWORD}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - APP_FRONTEND_URL=${APP_FRONTEND_URL}
      - FILE_UPLOAD_DIR=/app/uploads
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped
    networks:
      - default
      - event-net

  frontend:
    image: tanh11704/event-management-frontend:1.0
    container_name: event-management-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - event-net
      - default

volumes:
  mysql-data:
  redis-data:
  uploads:

networks:
  event-net:
    driver: bridge
