spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event_management?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  mail:
    username: tuanpham.5417@gmail.com
    password: fdbx epzc lutv mkcz

app:
  jwt:
    secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expirationMs: 900000
    refreshExpirationMs: 604800000
  cors:
    allowed-origins: "*"
  frontend:
    url: http://localhost:5173

cloudinary:
  cloud-name: dobtgdvzk
  api-key: 464153871671396
  api-secret: KRJlRPBureLOOq2L2fXCeKfwJEY

gemini:
  api:
    key: AIzaSyDSR-BEcj9XzUNxclgAq8gNfJg0WcwufzQ

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
